# Generated by Django 3.2 on 2021-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertizerdetail',
            name='user_category',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
