# Generated by Django 3.2 on 2021-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='campaign_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
