# Generated by Django 3.2 on 2021-04-30 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendeduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_type', models.CharField(max_length=50)),
                ('link', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('phnno', models.CharField(default='', max_length=12)),
                ('gender', models.CharField(max_length=8)),
                ('desc', models.TextField(default='', max_length=500)),
                ('tags', models.CharField(default='', max_length=50)),
                ('channel_logo', models.ImageField(default=None, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
