# Generated by Django 3.2 on 2021-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
