# Generated by Django 3.2 on 2021-05-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210503_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='channel_logo',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
