# Generated by Django 3.2 on 2021-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_extendeduser_channel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='channel_logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
