# Generated by Django 3.2 on 2021-05-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_extendeduser_channel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='channel_logo',
            field=models.ImageField(default=None, upload_to='user/channel_logo'),
        ),
    ]
