# Generated by Django 3.2 on 2021-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_extendeduser_channel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='firstname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='lastname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
