# Generated by Django 3.1.7 on 2021-05-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20210507_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='phnno',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='tags',
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
