# Generated by Django 3.2 on 2021-05-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210508_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='channel_logo',
        ),
    ]
