# Generated by Django 3.2 on 2021-05-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_extendeduser_channel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='channel_name',
        ),
    ]
