# Generated by Django 3.2 on 2021-05-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_extendeduser_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='search_query',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
