# Generated by Django 3.2 on 2021-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_extendeduser_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='id_store',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
