# Generated by Django 3.2 on 2021-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_extendeduser_id_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='firstname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='lastname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='phnno',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='tags',
            field=models.CharField(default='', max_length=50),
        ),
    ]
