# Generated by Django 3.2 on 2021-05-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210518_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='state',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
