# Generated by Django 3.2 on 2021-05-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
