# Generated by Django 3.2 on 2021-05-08 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_mostpopularvideo_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.CharField(max_length=50)),
                ('total_subs', models.CharField(max_length=50)),
                ('avg_views', models.CharField(default=None, max_length=50)),
                ('total_videos', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
