# Generated by Django 3.2 on 2021-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210508_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_statistics',
            name='avg_views',
            field=models.CharField(default='', max_length=50),
        ),
    ]
