# Generated by Django 3.2 on 2021-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210511_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_statistics',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='channel_statistics',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
