# Generated by Django 3.2 on 2021-05-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210511_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_statistics',
            name='language',
            field=models.CharField(default='', max_length=20),
        ),
    ]
