# Generated by Django 3.2 on 2021-05-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_channel_statistics_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_statistics',
            name='channel_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
