# Generated by Django 3.1.7 on 2021-05-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_channel_statistics_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_statistics',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
