# Generated by Django 3.2 on 2021-05-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_graphanalitycs_total_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphanalitycs',
            name='total_comment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
