# Generated by Django 3.2 on 2021-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_graphanalitycs_total_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphanalitycs',
            name='subsgoal_current_position_graph',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphanalitycs',
            name='substoviewratio_graph',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphanalitycs',
            name='views_to_like_graph',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
