# Generated by Django 3.2 on 2021-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210514_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_statistics',
            name='overall_marking',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
