# Generated by Django 3.2 on 2021-05-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210515_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_statistics',
            name='tags',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
