# Generated by Django 3.1.7 on 2021-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_channel_statistics_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_statistics',
            name='search_query',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
