# Generated by Django 3.2 on 2021-05-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_channel_statistics_search_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel_statistics',
            name='search_query',
        ),
    ]
